spring:
  profiles:
    include: config
  mail:
    port: 25
    host: ${freemarker.host}
    username: ${freemarker.username}
    password: ${freemarker.password}
    protocol: smtp
    default-encoding: utf-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}